# Conclusion

Through our exploratory data analysis of the world income inequality dataset, we found that income inequality is a global problem with long-lasting impact, particularly significant in developing countries such as Brazil and China. In highly developed countries such as the United States and Japan, the structure of income distribution tends to be more stable. The relationship between income distribution and GDP growth rate remains unclear, as no consistent trends were observed across groups of countries. From another perspective, the developing countries have higher GDP growth, while the developed countries are more stable, without any surge in their GDP growth. This can imply that the status of a country's development is more crucial to reflect its resilience to income inequality. Our analysis has several **(limitations)**, the most significant being the lack of complete data. If we could collect relevant data for every country each year, we would be able to conduct a more comprehensive regional trend analysis. During the analysis, we relied solely on the information provided by the WIID dataset to analyze factors contributing to income inequality. **(For future research)**, we hope to include more detailed economic data, such as demographic changes, inflation rates, stock prices, and other relevant metrics. This would allow for deeper analysis aimed at uncovering more valuable insights and identifying additional factors contributing to income inequality, as well as potential solutions. The most important **(lesson we learned)** from this project was how to collaborate using GitHub to manage workflows. We believe that starting this project from scratch, reading the data, discussing and deciding on the types of plots to use, and determining the information to include has been an invaluable experience.